#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Nitty.Droid.Resource", IsApplication=true)]

namespace Nitty.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_addprofile = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_checkmark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int GenderLabel = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int NameLabel = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int NotesLabel = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int buttonBegin = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int buttonProfile = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int buttonResults = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int buttonTest = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int checkMark = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int checkmark = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int chkDone = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int lblDescription = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int lblName = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int lblScore = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int lstProfiles = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int menu_add_profile = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int menu_delete_profile = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int menu_save_profile = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int radGroupGender = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int radioFemale = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int radioMale = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int relativeLayout1 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int textView1 = 2131165204;
			
			// aapt resource value: 0x7f070005
			public const int txtName = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int txtNotes = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseProfileScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OptionsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProfileDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProfileListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScoreListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WelcomeScreen = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_detailsscreen = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_homescreen = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int begin_text = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int display_title = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int female = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int male = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int results = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int retakeTest = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int signIn = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int signOut = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int takeTest = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_TaskyPro = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
